# Setup
title: The 34th Meeting of Computational Linguistics in The Netherlands.
url: https://hielkemuizelaar.github.io
avatar: /logo_placeholder.png
paginate: 10
paginate_per_page: 10
permalink: pretty
cover_image: /ul.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: hielkemuizelaar
  card: summary
logo: logo.png
social:
  name: Hielke Muizelaar
  links:
    - https://twitter.com/hielkemuizelaar
    - https://github.com/hielkemuizelaar
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  # name: Hielke Muizelaar
  # url: https://github.com/hielkemuizelaar/
  email: clin34@leidenuniv.nl
